-- Auto-generated by generate-eventops-sample-data.js. Do not edit by hand.
USE jobfair;

DELETE FROM equipment_requests;
DELETE FROM booths;
DELETE FROM banners;
DELETE FROM special_requirements;
DELETE FROM company_delegates;
DELETE FROM company_attendance;
DELETE FROM student_attendance_view;
DELETE FROM event_schedule;
DELETE FROM access_passes;
DELETE FROM attendance_staff;
DELETE FROM event_ops_audit_log;
DELETE FROM casto_team_members;
DELETE FROM settings WHERE `key` = 'surveyPublic';

INSERT INTO booths (legacy_id, number, zone, ring, company_name, company_id, booth_type, status, updated_by, updated_at) VALUES
(1, 'B01', 'A', 'outer', 'Emirates NBD', NULL, 'Premium', 'Assigned', 'Rana', '2026-06-28 10:12:00'),
(2, 'B02', 'A', 'outer', 'Etisalat', NULL, 'Standard', 'Assigned', 'Rana', '2026-06-28 10:20:00'),
(3, 'B03', 'A', 'outer', NULL, NULL, 'Standard', 'Available', 'Rana', '2026-06-25 09:00:00'),
(4, 'B04', 'A', 'outer', NULL, NULL, 'Corner', 'Available', 'Rana', '2026-06-25 09:00:00'),
(5, 'B05', 'B', 'outer', 'Dubai Police', NULL, 'Premium', 'Assigned', 'Prithba', '2026-06-29 14:05:00'),
(6, 'B06', 'B', 'outer', NULL, NULL, 'Standard', 'Reserved', 'Rana', '2026-06-29 15:40:00'),
(7, 'B07', 'B', 'outer', 'DP World', NULL, 'Corner', 'Assigned', 'Rana', '2026-06-29 16:22:00'),
(8, 'B08', 'B', 'outer', NULL, NULL, 'Standard', 'Available', 'Rana', '2026-06-25 09:00:00'),
(9, 'B09', 'C', 'center', NULL, NULL, 'Standard', 'Reserved', 'Prithba', '2026-06-30 11:08:00'),
(10, 'B10', 'C', 'center', NULL, NULL, 'Standard', 'Available', 'Rana', '2026-06-25 09:00:00'),
(11, 'B11', 'C', 'center', 'ADNOC', NULL, 'Premium', 'Assigned', 'Rana', '2026-06-30 12:45:00'),
(12, 'B12', 'C', 'center', NULL, NULL, 'Corner', 'Available', 'Rana', '2026-06-25 09:00:00');

INSERT INTO banners (legacy_id, company_name, company_id, material, size, quantity, artwork, contact, deadline, status, notes, updated_by, updated_at) VALUES
(1, 'Emirates NBD', NULL, 'Roll-up Banner', '85 × 200 cm', 2, 'enbd-rollup-v3.pdf', 'Sara Al Mansouri', '2026-07-05', 'Placed', '2 roll-ups, logo updated', 'Aseel', '2026-06-30 09:30:00'),
(2, 'Etisalat', NULL, 'Backdrop', '300 × 200 cm', 1, 'etisalat-backdrop.ai', 'Aisha Noor', '2026-07-05', 'Printed', 'Awaiting delivery', 'Aseel', '2026-06-30 13:15:00'),
(3, 'Dubai Police', NULL, 'Table Skirt', '180 × 75 cm', 3, 'dxb-police-skirt.pdf', 'Lt. Hessa Al Zaabi', '2026-07-06', 'Approved', 'Standard green theme', 'Aseel', '2026-06-29 16:40:00'),
(4, 'DP World', NULL, 'Digital Screen Graphic', '1920 × 1080 px', 1, 'dpworld-screen.mp4', 'HR Director', '2026-07-04', 'Submitted', 'HD resolution required', 'Aseel', '2026-06-30 10:05:00'),
(5, 'ADNOC', NULL, 'Roll-up Banner', '85 × 200 cm', 2, NULL, '—', '2026-07-05', 'Not Submitted', 'Follow up needed', 'Aseel', '2026-06-28 11:00:00');

INSERT INTO special_requirements (legacy_id, company_name, company_id, description, category, priority, status, notes, updated_by, updated_at) VALUES
(1, 'Emirates NBD', NULL, 'Extra monitor for presentations', 'AV Equipment', 'High', 'In Progress', '32" screen requested', 'Prithba', '2026-06-30 09:10:00'),
(2, 'Etisalat', NULL, 'Wheelchair accessible booth positioning', 'Accessibility', 'Critical', 'Fulfilled', 'Booth B02 repositioned', 'Prithba', '2026-06-29 15:30:00'),
(3, 'Dubai Police', NULL, 'Uniform mannequin display', 'Display', 'Medium', 'Open', 'Needs stand and lighting', 'Prithba', '2026-06-29 10:00:00'),
(4, 'DP World', NULL, 'VIP lounge seating nearby', 'Comfort', 'Low', 'Open', 'Pending space review', 'Rana', '2026-06-28 14:20:00'),
(5, 'ADNOC', NULL, 'Dedicated power line 30A', 'Power', 'Critical', 'In Progress', 'Electrician scheduled', 'Prithba', '2026-06-30 16:55:00');

INSERT INTO equipment_requests (legacy_id, entity_label, booth_id, item, qty_requested, qty_fulfilled, status, updated_by, updated_at) VALUES
(1, 'Emirates NBD / B01', (SELECT id FROM booths WHERE legacy_id = 1), 'Folding Table', 2, 2, 'Fulfilled', 'Prithba', '2026-06-29 09:00:00'),
(2, 'Emirates NBD / B01', (SELECT id FROM booths WHERE legacy_id = 1), 'Chair', 4, 4, 'Fulfilled', 'Prithba', '2026-06-29 09:05:00'),
(3, 'Etisalat / B02', (SELECT id FROM booths WHERE legacy_id = 2), 'Power Strip (6-way)', 2, 1, 'Partial', 'Prithba', '2026-06-30 11:30:00'),
(4, 'Etisalat / B02', (SELECT id FROM booths WHERE legacy_id = 2), 'Monitor Stand', 1, 0, 'Pending', 'Prithba', '2026-06-30 11:32:00'),
(5, 'Dubai Police / B05', (SELECT id FROM booths WHERE legacy_id = 5), 'Folding Table', 3, 3, 'Fulfilled', 'Prithba', '2026-06-29 13:45:00'),
(6, 'Dubai Police / B05', (SELECT id FROM booths WHERE legacy_id = 5), 'Display Screen 43"', 1, 1, 'Fulfilled', 'Prithba', '2026-06-29 13:50:00'),
(7, 'DP World / B07', (SELECT id FROM booths WHERE legacy_id = 7), 'Chair', 6, 4, 'Partial', 'Prithba', '2026-06-30 15:10:00'),
(8, 'DP World / B07', (SELECT id FROM booths WHERE legacy_id = 7), 'Extension Cable 10m', 2, 2, 'Fulfilled', 'Prithba', '2026-06-30 15:12:00');

INSERT INTO company_delegates (company_name, company_id, name, role, email, phone, badge_status) VALUES
('Emirates NBD', NULL, 'Sara Al Mansouri', 'HR Manager', 'sara.m@enbd.ae', '+971 50 111 2233', 'Printed'),
('Emirates NBD', NULL, 'Khalid Rashid', 'Recruiter', 'k.rashid@enbd.ae', '+971 55 444 5566', 'Pending'),
('Etisalat', NULL, 'Aisha Noor', 'Talent Acquisition', 'aisha.n@etisalat.ae', '+971 52 777 8899', 'Printed'),
('Etisalat', NULL, 'Mohammed Al Ali', 'Campus Relations', 'm.alali@etisalat.ae', '+971 56 223 3445', 'Printed'),
('Etisalat', NULL, 'Fatima Hamdan', 'HR Coordinator', 'f.hamdan@etisalat.ae', '+971 50 998 1122', 'Pending'),
('Dubai Police', NULL, 'Maj. Ahmed Karimi', 'Recruitment Officer', 'a.karimi@dubaipolice.gov.ae', '+971 4 999 0011', 'Printed'),
('Dubai Police', NULL, 'Lt. Hessa Al Zaabi', 'HR Specialist', 'h.alzaabi@dubaipolice.gov.ae', '+971 4 999 0022', 'Pending');

INSERT INTO company_attendance (booth_number, company_name, company_id, delegate_count, checked_in_count, check_in_time, method, status, updated_by, updated_at) VALUES
('B01', 'Emirates NBD', NULL, 2, 2, '08:45', 'QR', 'Present', 'Maha', '2026-06-30 08:45:00'),
('B02', 'Etisalat', NULL, 3, 2, '09:10', 'QR', 'Partial', 'Maha', '2026-06-30 09:10:00'),
('B05', 'Dubai Police', NULL, 2, 0, '—', '—', 'Absent', 'Maha', '2026-06-30 08:00:00'),
('B07', 'DP World', NULL, 2, 2, '08:55', 'QR', 'Present', 'Maha', '2026-06-30 08:55:00'),
('B11', 'ADNOC', NULL, 2, 0, '—', '—', 'Absent', 'Maha', '2026-06-30 08:00:00');

INSERT INTO student_attendance_view (uni_id, applicant_id, student_name, check_in_time, method, status) VALUES
('202110001', NULL, 'Layla Hassan', '09:05', 'QR', 'Checked In'),
('202110045', NULL, 'Omar Al Farsi', '09:12', 'QR', 'Checked In'),
('202110089', NULL, 'Nour Ibrahim', '09:30', 'Manual', 'Checked In'),
('202110120', NULL, 'Reem Sultan', '09:44', 'QR', 'Checked In'),
('202110200', NULL, 'Faisal Ahmed', '—', '—', 'Pending'),
('202110234', NULL, 'Amira Khalil', '10:05', 'QR', 'Checked In');

INSERT INTO event_schedule (legacy_id, start_time, end_time, title, host, location, capacity, registered, status, updated_by, updated_at) VALUES
(1, '08:30', '09:00', 'Registration & Venue Setup', 'Event Team', 'Main Entrance', 300, 280, 'Ended', 'Rana', '2026-06-20 10:00:00'),
(2, '09:00', '09:30', 'Opening Ceremony & Welcome Address', 'University President', 'Main Hall', 500, 420, 'Ended', 'Rana', '2026-06-20 10:05:00'),
(3, '09:30', '12:00', 'Open Networking — Booth Visits', 'All Companies', 'Exhibition Floor', 1000, 850, 'Live', 'Rana', '2026-06-20 10:10:00'),
(4, '12:00', '13:00', 'Lunch Break', 'Catering Team', 'Cafeteria', 400, 370, 'Upcoming', 'Rana', '2026-06-20 10:15:00'),
(5, '13:00', '15:30', 'Resume Drop & Interview Sessions', 'All Companies', 'Exhibition Floor', 1000, 760, 'Upcoming', 'Rana', '2026-06-20 10:20:00'),
(6, '15:30', '16:00', 'Closing & Prize Distribution', 'Event Coordinator', 'Main Stage', 300, 210, 'Upcoming', 'Rana', '2026-06-20 10:25:00');

INSERT INTO access_passes (legacy_id, company_name, delegate, pass_type, code, issued_date, status, slot, location, updated_by, updated_at) VALUES
(1, 'Emirates NBD', 'Sara Al Mansouri', 'Entry', 'ENT-ENB-001', '2026-06-18', 'Active', NULL, NULL, 'Yousef', '2026-06-18 09:00:00'),
(2, 'Emirates NBD', 'Khalid Rashid', 'Entry', 'ENT-ENB-002', '2026-06-18', 'Active', NULL, NULL, 'Yousef', '2026-06-18 09:02:00'),
(3, 'Etisalat', 'Aisha Noor', 'Entry', 'ENT-ETS-001', '2026-06-18', 'Used', NULL, NULL, 'Yousef', '2026-06-18 09:04:00'),
(4, 'Etisalat', 'Mohammed Al Ali', 'Parking', 'PRK-ETS-002', '2026-06-18', 'Active', 'P1-14', 'Level 1, North Lot, near Gate B', 'Yousef', '2026-06-18 09:06:00'),
(5, 'Etisalat', 'Fatima Hamdan', 'Entry', 'ENT-ETS-003', '2026-06-18', 'Active', NULL, NULL, 'Yousef', '2026-06-18 09:08:00'),
(6, 'Dubai Police', 'Maj. Ahmed Karimi', 'Entry', 'ENT-DXB-001', '2026-06-18', 'Revoked', NULL, NULL, 'Yousef', '2026-06-19 14:30:00'),
(7, 'DP World', 'Logistics Lead', 'Parking', 'PRK-DPW-001', '2026-06-18', 'Active', 'P2-03', 'Level 2, South Lot, ramp entrance', 'Yousef', '2026-06-18 09:10:00'),
(8, 'DP World', 'HR Director', 'Entry', 'ENT-DPW-002', '2026-06-18', 'Active', NULL, NULL, 'Yousef', '2026-06-18 09:12:00');

INSERT INTO attendance_staff (legacy_id, name, email, phone, code, status, updated_by, updated_at) VALUES
(1, 'Volunteer Desk 1', 'volunteer1@example.com', '', 'DESK1', 'active', 'Maha', '2026-06-28 09:00:00'),
(2, 'Volunteer Desk 2', 'volunteer2@example.com', '', 'DESK2', 'invited', 'Maha', '2026-06-28 09:01:00');

INSERT INTO event_ops_audit_log (legacy_id, occurred_at, actor_name, section, message) VALUES
(1, '2026-06-30 12:45:00', 'Rana', 'Venue & Booths', 'Assigned booth B11 to ADNOC'),
(2, '2026-06-30 13:15:00', 'Aseel', 'Banners', 'Marked Etisalat backdrop as Printed'),
(3, '2026-06-30 15:10:00', 'Prithba', 'Equipment', 'Updated DP World chair delivery (4 of 6)'),
(4, '2026-06-30 16:55:00', 'Prithba', 'Requirements', 'Started ADNOC dedicated power line request');

INSERT INTO casto_team_members (id, name, role, focus_modules, responsibilities) VALUES
('rana', 'Rana', 'Event Lead', '["venue","schedule","report"]', 'Owns the venue floor plan and booth assignments, builds the event-day schedule, and compiles the post-event report. Final point of contact for anything not covered by another module.'),
('prithba', 'Prithba', 'Logistics & Equipment', '["equipment","requirements"]', 'Handles all equipment requests (tables, chairs, power, screens) and special requirements raised by companies (accessibility, AV, custom setups).'),
('aseel', 'Aseel', 'Branding & Media', '["banners"]', 'Tracks every company\'s banner and branding assets from submission through printing to placement on-site.'),
('maha', 'Maha', 'Attendance & Check-in', '["attendance","delegates"]', 'Runs check-in on event day (booth QR scans and student check-in) and manages the company delegate list and badge printing.'),
('yousef', 'Yousef', 'Access & Passes', '["passes"]', 'Issues and manages entry and parking access passes for every company delegate, including parking slot assignments.');

INSERT INTO settings (`key`, value, updated_by) VALUES
('surveyPublic', 'false', NULL);
